### ISSUE TITLE
More files missing from solution

### ISSUE THREAD

**Issue by amrender** [pcarrasco23/FootlooseFinancialServices#2]
Hi,
Thanks for quick update. Could you check , there are some more files missing from the solution.
Probably you should download the whole solution  from scratch and identify the gaps.
Thanks

**Comment by amrender** [comment]
FootlooseFinancialServices-master\FootlooseFS.DataPersistence\packages.config
FootlooseFinancialServices-master\FootlooseFS.EnterpriseService\web.config
and more!!

**Comment by pcarrasco23** [comment]
Thanks for checking. I added the missing packages. The missing web and app configs were intentional because of sensitive data. You can use the web.config.sample and rename them appropriately. I will do that though today and add any additional files that are missing.

**Comment by pcarrasco23** [comment]
I also corrected the hints for the Entity framework reference in a couple of the projects.
